#ifndef ENGINEERPROJECT_ERRORS_H
#define ENGINEERPROJECT_ERRORS_H

//error codes
enum ErrorCodes {
    SUCCESS = 0,
    ERR_WRG_ORDR,
    ERR_OPEN_FILE,
    ERR_CLOSE_FILE,
    ERR_READ_DATA,
    GNRT_DATA_FAIL,
    BBL_SORT_FAIL,
    QCK_SORT_FAIL,
    MRG_SORT_FAIL,
    INS_SORT_FAIL,
    HP_SORT_FAIL,
    SLC_SORT_FAIL,
    SHL_SORT_FAIL,
    CRA_SORT_FAIL,
    DRAW_NMBR_FAIL,
    SEARCH_FAIL,
    LNR_SEARCH_FAIL,
    GRD_SEARCH_FAIL,
    BNR_SEARCH_FAIL,
    EXTR_SEARCH_FAIL,
};

#endif //ENGINEERPROJECT_ERRORS_H
